name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'AzureDevOps') }}
    runs-on: ubuntu-latest
    steps:
      - name: Starting
        run: echo "Starting"

      - name: Echo Issue Information
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}"
      
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "kbsoftware-dk"
          ado_project: "KBSyncTest"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
